### PR TITLE
hautelook/AliceBundle fixtures setup [WIP]

### PR DESCRIPTION
**Pull request by szymach**

### CODE REVIEW

**Comment by norzechowicz** [comment]
what exactly is the reason for adding this hard dependency from external bundle here?

**Comment by szymach** [comment]
The reason is that we use it in our projects now and it comes in handy when dealing with fixtures.

**Comment by szymach** [comment]
Anyways, I will move it to suggested dependencies and load the services / compiler passes conditionally.

**Comment by norzechowicz** [comment]
It would be better to create standalone external library (bridge) that will hold those compiler passes. This bundle (and any other) does not needs alice and let it keep it that way.

**Comment by chives** [comment]
we don't want to create another library for such a small feature. i think that suggested dependency is some kind of compromise

**Comment by norzechowicz** [comment]
when bundle gets new dependency it needs to support it at least to the next major version. For the very same reason we can't updated admin-bundle to sf3 because we decided once to make bundles depends on others. Its not only a dependnecy from bundle, its a dependency from that bundle dependnecies also.

**Pull request closed without merging**
